steps:
  # Step 1 — Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'order-consumer'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:$BUILD_ID'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:latest'
      - '.'

  # Step 2 — Push BUILD_ID tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:$BUILD_ID'

  # Step 3 — Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:latest'

  # Step 4 — Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'order-consumer'
      - '--image=asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:latest'
      - '--platform=managed'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--timeout=300s'
      - '--set-env-vars=SMTP_HOST=smtp.gmail.com,SMTP_PORT=587,SMTP_SECURE=false,SMTP_USER=vamsir673@gmail.com,SMTP_PASS=hovhhdfpotkurgef,EMAIL_FROM="Vamshi Fitness <vamsir673@gmail.com>"'

images:
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:$BUILD_ID'
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/order-consumer:latest'

options:
  logging: CLOUD_LOGGING_ONLY
